version: '3'
networks:
  xmtp:
services:
  waku-node:
    image: xmtp/node-go:dev
    environment:
      - GOWAKU-NODEKEY=8a30dcb604b0b53627a5adc054dbf434b446628d4bd1eccc681d223f0550ce67
    command:
      - --ws
      - --store
      - --lightpush
      - --filter
      - --ws-port=9001
      - --db-connection-string=postgres://postgres:xmtp@postgres:5432/postgres?sslmode=disable
    ports:
      - 9001:9001
    networks:
      - xmtp
  postgres:
    image: postgres:13
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: xmtp
    networks:
      - xmtp
