services:
  waku-node:
    image: xmtp/node-go:dev
    environment:
      - GOWAKU-NODEKEY=8a30dcb604b0b53627a5adc054dbf434b446628d4bd1eccc681d223f0550ce67
    command:
      - --ws
      - --store
      - --lightpush
      - --filter
      - --ws-port=9001
      - --db-connection-string=postgres://postgres:xmtp@postgres:6543/postgres?sslmode=disable
    ports:
      - 9001:9001
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: xmtp
    ports:
      # Use an alternate port to not conflict with other Postgres instances
      - 6543:5432
